# CMake generated Testfile for 
# Source directory: /home/ubuntu/mirlox/mir
# Build directory: /home/ubuntu/mirlox/mir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(varr-test "varr_test")
set_tests_properties(varr-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;91;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(dlist-test "dlist_test")
set_tests_properties(dlist-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;92;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(bitmap-test "bitmap_test")
set_tests_properties(bitmap-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;93;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(htab-test "htab_test")
set_tests_properties(htab-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;94;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(reduce-test "reduce_test" "/home/ubuntu/mirlox/mir/c2mir/c2mir.c")
set_tests_properties(reduce-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;95;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(simplify-test "simplify_test")
set_tests_properties(simplify-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;107;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(scan-test "scan_test")
set_tests_properties(scan-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;108;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(io-test "io_test")
set_tests_properties(io-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;109;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test1 "interp_loop")
set_tests_properties(interp-test1 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;156;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test2 "interp_loop_c")
set_tests_properties(interp-test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;157;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test3 "interp_sieve")
set_tests_properties(interp-test3 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;158;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test4 "interp_sieve_c")
set_tests_properties(interp-test4 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;159;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test5 "interp_hi")
set_tests_properties(interp-test5 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;160;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test6 "interp_args")
set_tests_properties(interp-test6 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;161;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test7 "interp_args_c")
set_tests_properties(interp-test7 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;162;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test8 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test8.mir")
set_tests_properties(interp-test8 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;165;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test9 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test9.mir")
set_tests_properties(interp-test9 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;165;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test10 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test10.mir")
set_tests_properties(interp-test10 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;165;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test11 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test11.mir")
set_tests_properties(interp-test11 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;169;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test12 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test12.mir")
set_tests_properties(interp-test12 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;170;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test13 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test13.mir")
set_tests_properties(interp-test13 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;174;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test14 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test14.mir")
set_tests_properties(interp-test14 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;174;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test15 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test15.mir")
set_tests_properties(interp-test15 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;174;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(interp-test16 "run_test" "-i" "/home/ubuntu/mirlox/mir/mir-tests/test16.mir")
set_tests_properties(interp-test16 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;174;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test1 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test1.mir")
set_tests_properties(gen-test1 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test2 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test2.mir")
set_tests_properties(gen-test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test3 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test3.mir")
set_tests_properties(gen-test3 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test4 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test4.mir")
set_tests_properties(gen-test4 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test5 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test5.mir")
set_tests_properties(gen-test5 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test6 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test6.mir")
set_tests_properties(gen-test6 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test7 "run_test" "-d" "/home/ubuntu/mirlox/mir/mir-tests/test7.mir")
set_tests_properties(gen-test7 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;180;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test8 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test8.mir")
set_tests_properties(gen-test8 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;184;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test9 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test9.mir")
set_tests_properties(gen-test9 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;184;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test10 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test10.mir")
set_tests_properties(gen-test10 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;184;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test11 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test11.mir")
set_tests_properties(gen-test11 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;188;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test12 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test12.mir")
set_tests_properties(gen-test12 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;189;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test13 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test13.mir")
set_tests_properties(gen-test13 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;193;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test14 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test14.mir")
set_tests_properties(gen-test14 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;193;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test15 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test15.mir")
set_tests_properties(gen-test15 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;193;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test16 "run_test" "-g" "/home/ubuntu/mirlox/mir/mir-tests/test16.mir")
set_tests_properties(gen-test16 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;193;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test-loop "gen_loop")
set_tests_properties(gen-test-loop PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;206;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(gen-test-sieve "gen_sieve")
set_tests_properties(gen-test-sieve PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;207;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(readme-example-test "readme_example")
set_tests_properties(readme-example-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;215;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(mir2c-test "mir2c_test")
set_tests_properties(mir2c-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;224;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
add_test(c2mir-simple-test "c2m" "-v" "/home/ubuntu/mirlox/mir/sieve.c" "-ei")
set_tests_properties(c2mir-simple-test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/mirlox/mir/CMakeLists.txt;228;add_test;/home/ubuntu/mirlox/mir/CMakeLists.txt;0;")
